# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Docker CI

on:
  push:
    branches: [ feature/docker-ci ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v3
    
    - 
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - 
      name: Build with Maven
      env:
        SPRING_PROFILES_ACTIVE: secret
        PG_URL: ${{ secrets.VM_URL }}
        PG_USERNAME: ${{ secrets.VM_USERNAME }}
        PG_PASSWORD: ${{ secrets.VM_PASSWORD }}
      run: |
        mvn clean install -f ./backend-services/api-gateway/pom.xml spring-boot:start
        mvn clean install -f ./backend-services/favor/pom.xml spring-boot:start

    - 
      name: Build Docker Images
      run: |
        docker build -t gmtang/favor8_api-gateway ./backend-services/api-gateway
        docker build -t gmtang/favor8_kafka-consumer ./backend-services/favor8
        
    - 
      name: Push to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push gmtang/favor8_api-gateway:m3
        docker push gmtang/favor8_kafka-consumer:m3
